apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: andreslonmednet 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: andreslonmednet 
    spec:
      containers:
        - name: andreslonmednet 
          image: andreslonacr.azurecr.io/andreslonmednet 
          ports:
          - containerPort: 80